

S3_RESPONSE_FILES_NEW = 'response/files/new'
S3_RESPONSE_FILES_IMPORTED = 'response/files/imported'
S3_RESPONSE_FILES_FAILED = 'response/files/failed'
S3_RESPONSE_FILES_TESTING = 'response/files/test'
S3_RESPONSE_FILES_EXPORTED = 'response/files/exported'

S3_RESPONSE_QUALTRICS_NEW = 'response/qualtrics/new'
S3_RESPONSE_QUALTRICS_IMPORTED = 'response/qualtrics/imported'
S3_RESPONSE_QUALTRICS_FAILED = 'response/qualtrics/failed'
S3_RESPONSE_QUALTRICS_TESTING = 'response/qualtrics/test'
S3_RESPONSE_QUALTRICS_EXPORTED = 'response/qualtrics/exported'

CSV_FILE_EXTENSION = 'csv'
JSON_FILE_EXTENSION = 'json'
ZIP_FILE_EXTENSION = 'zip'

CHUNK_SIZE_FILE_PROCESSOR = 25
CHUNK_SIZE_RESPONSE_COMBINER = 500


ROW_NUMBER_LABEL = 'row_number'

PREVENT_DUPLICATE_QUESTION_LABELS_WITH_INDEX_SUFFIXES = True

UNLABELLED_PLACEHOLDER = 'unlabelled'
VALID_LABEL_REGEX = '^(?!.*__.*)[a-z0-9_]+$'
SURVEY_COMPLETED_LABEL = 'survey_completed'
RESEARCHER_NAME_LABEL = 'researcher_name'
RESPONDENT_NAME_LABEL = 'respondent_name'
RESPONDENT_EMAIL_LABEL = 'respondent_email'
RESPONDENT_FIRST_NAME_LABEL = 'respondent_first_name'
RESPONDENT_LAST_NAME_LABEL = 'respondent_last_name'
RESPONDENT_PHONE_LABEL = 'respondent_phone_num'
RESPONDENT_LOCATION_LABELS = ['customer_town', 'respondent_town', 'mis_regionvillage']
RESPONDENT_IP_LABEL = 'respondent_ip'
RESPONDENT_COMPANY_LABEL = 'respondent_company'

CUSTOMER_LABEL_PREFIX = 'customer_'
RESPONDENT_LABEL_PREFIX = 'respondent_'

NPS_COMPANY_QUESTION_LABEL = 'nps_company_rating'
NPS_PRODUCT_QUESTION_LABEL = 'nps_product_rating'

QOL_QUESTION_LABEL = 'qol_rating'
QOL_ANSWER_VERY_MUCH_IMPROVED = 'very much improved'
QOL_ANSWER_SLIGHTLY_IMPROVED = ['slightly improved', 'slight improved']

ALTERNATIVES_QUESTION_LABEL = 'alternatives_yn'
ALTERNATIVES_ANSWER_YES = 'yes'
ALTERNATIVES_ANSWER_NO = ['no', 'not sure']
ALTERNATIVES_ANSWER_MAYBE = 'maybe'

FEEDBACK_CHALLENGE_QUESTION_LABEL = 'challenges_yn'
FEEDBACK_CHALLENGE_ANSWER_YES = 'yes'
FEEDBACK_CHALLENGE_ANSWER_NO = 'no'

CHALLENGE_RESOLVED_QUESTION_LABEL = 'challenges_resolve_yn'
CHALLENGE_RESOLVED_ANSWER_STRONGLY_AGREE = 'strongly agree'
CHALLENGE_RESOLVED_ANSWER_AGREE = 'agree'
CHALLENGE_RESOLVED_ANSWER_SOMEWHAT_AGREE = 'somewhat agree'
CHALLENGE_RESOLVED_ANSWER_NEITHER = 'neither agree nor disagree'
CHALLENGE_RESOLVED_ANSWER_SOMEWHAT_DISAGREE = 'somewhat disagree'
CHALLENGE_RESOLVED_ANSWER_DISAGREE = 'disagree'
CHALLENGE_RESOLVED_ANSWER_STRONGLY_DISAGREE = 'strongly disagree'
CHALLENGE_RESOLVED_ONE_PERCENT_AS_DECIMAL = 0.04

BENCHMARK_SECTOR_NAMES = ['Agriculture', 'Education', 'Energy', 'Gender']
ALL = 'All'


QUESTION_TYPE_DATE_CODE = 'date'
QUESTION_TYPE_MULTIPLE_CHOICE_CODE = 'mc'
QUESTION_TYPE_NUMERIC_CODE = 'num'
QUESTION_TYPE_OPEN_ENDED_CODE = 'oe'
QUESTION_TYPE_RATING_CODE = 'rating'
QUESTION_TYPE_UNKNOWN_CODE = 'unknown'
QUESTION_TYPE_YES_NO_CODE = 'yn'

QUESTION_TYPE_DATE_TYPE = 'date'
QUESTION_TYPE_MULTIPLE_CHOICE_TYPE = 'multiple-choice'
QUESTION_TYPE_NUMERIC_TYPE = 'numeric'
QUESTION_TYPE_OPEN_ENDED_TYPE = 'open-ended'
QUESTION_TYPE_RATING_TYPE = 'rating'
QUESTION_TYPE_UNKNOWN_TYPE = 'unknown'
QUESTION_TYPE_YES_NO_TYPE = 'yes-no'

MULTIPLE_CHOICE_ANSWER_SEPARATOR = '|'


QUALTRICS_API_BLOCK_VISIBILITY_EXPANDED = 'Expanded'
QUALTRICS_API_EXPORT_RESPONSES_RETRY_LIMIT = 5
QUALTRICS_API_EXPORT_RESPONSES_PROGRESS_TIMEOUT = 3
QUALTRICS_API_PATH_BLOCKS = 'blocks'
QUALTRICS_API_PATH_EXPORT_RESPONSES = 'export-responses'
QUALTRICS_API_PATH_QUESTIONS = 'questions'
QUALTRICS_API_PATH_SURVEY_DEFINITIONS = 'survey-definitions'
QUALTRICS_API_PATH_SURVEY_VERSIONS = 'survey-definitions/{}/versions'
QUALTRICS_API_PATH_SURVEYS = 'surveys'
QUALTRICS_API_PUBLISHED_SURVEY_URL_PATTERN = 'https://survey.eu.qualtrics.com/jfe/form/{}'
QUALTRICS_API_REGEX_BLOCK_ID = '^BL_[a-zA-Z0-9]{11,15}$'
QUALTRICS_API_REGEX_QUESTION_ID = '^QID[a-zA-Z0-9]+$'
QUALTRICS_API_REGEX_RESPONSE_ID = '^R_[A-Za-z0-9]{11,15}'
QUALTRICS_API_REGEX_SURVEY_ID = '^SV_[a-zA-Z0-9]{11,15}$'
QUALTRICS_API_REQUIRED_QUESTION_PARAM_KEYS = [
    'text', 'tag_number', 'type', 'answer_selector',
    'label', 'is_mandatory', 'translations',
    'block_number',
]
QUALTRICS_API_REQUIRED_QUESTION_PAYLOAD_KEYS = [
    'QuestionText', 'DataExportTag', 'QuestionType', 'Selector', 'Configuration',
    'QuestionDescription', 'Validation', 'Language',
]
QUALTRICS_API_DEFAULT_BLOCK_TYPE = 'Default'
QUALTRICS_API_STANDARD_BLOCK_TYPE = 'Standard'
QUALTRICS_API_QUESTION_TYPE_MC = 'MC'
QUALTRICS_API_QUESTION_TYPE_TE = 'TE'
QUALTRICS_API_SUPPORTED_ANSWER_SELECTORS = [
    'DL', 'GRB', 'MACOL', 'MAHR', 'MAVR', 'MSB',
    'SACOL', 'SAHR', 'SAVR', 'SB', 'TB', 'TXOT', 'PTB', 'SL',
]
QUALTRICS_API_SUPPORTED_BLOCK_TYPES = ['Standard', 'Default', 'Trash']
QUALTRICS_API_SUPPORTED_DISPLAY_LOGIC_CHOICE_LOCATORS = [None, 'SelectableChoice']
QUALTRICS_API_SUPPORTED_DISPLAY_LOGIC_CONJUNCTIONS = [None, 'Or']
QUALTRICS_API_SUPPORTED_DISPLAY_LOGIC_OPERATORS = ['EqualTo', 'Selected', 'Is']
QUALTRICS_API_SUPPORTED_LANGUAGE_CODES = [
    'AR', 'ASM', 'AZ-AZ', 'BEL', 'BG', 'BN', 'BS', 'CA', 'CEB', 'CH', 'CS', 'CY', 'DA', 'DE',
    'EL', 'EN-GB', 'EN-US', 'EN', 'EO', 'ES-ES', 'ES', 'ET', 'FA', 'FI', 'FR-CA', 'FR', 'GU',
    'HE', 'HE-ZA', 'HI', 'HIL', 'HR', 'HU', 'HYE', 'ID', 'ISL', 'IT', 'JA', 'KAN', 'KAT', 'KAZ',
    'KM', 'KO', 'LT', 'LV', 'MAL', 'MAR', 'MK', 'MN', 'MS', 'MY', 'NL', 'NO', 'ORI', 'PA-IN',
    'PL', 'PT-BR', 'PT', 'RO', 'RU', 'SIN', 'SK', 'SL', 'SQI', 'SR-ME', 'SR', 'SV', 'SW', 'TA',
    'TEL', 'TGL', 'TH', 'TR', 'UK', 'UR', 'VI', 'ZH-S', 'ZH-T',
]
QUALTRICS_API_SUPPORTED_PROJECT_CATEGORIES = ['CORE', 'CX', 'EX', 'BX', 'PX']
QUALTRICS_API_SUPPORTED_QUESTION_TYPES = [
    'MC', 'Matrix', 'Captcha', 'CS', 'DB', 'DD', 'Draw', 'DynamicMatrix', 'FileUpload', 'GAP',
    'HeatMap', 'HL', 'HotSpot', 'Meta', 'PGR', 'RO', 'SBS', 'Slider', 'SS', 'TE', 'Timing',
]

ENV_VAR_QUALTRICS_API_BASE_URL = 'QUALTRICS_API_BASE_URL'
ENV_VAR_QUALTRICS_API_INTERNAL_AUTH_TOKEN = 'QUALTRICS_API_INTERNAL_AUTH_TOKEN'
ENV_VAR_QUALTRICS_API_EXTERNAL_AUTH_TOKEN = 'QUALTRICS_API_EXTERNAL_AUTH_TOKEN'


PROJECT_CODE_ZERO_PAD_LENGTH = 3
PLATFORM_PROJECT_CODE_PREFIX = '60DB'

QUESTION_TEXT_DEFAULT_LANGUAGE_CODE = 'en'


SIXTYDB_QUESTION_TYPE_MULTIPLE_CHOICE = 'multiple-choice'
SIXTYDB_QUESTION_TYPE_UNKNOWN = 'unknown'
SIXTYDB_QUESTION_CATEGORY_UNKNOWN = 'unknown'
